### ISSUE TITLE
Fix CI issue & update kivy installation

### ISSUE THREAD

**Issue by unsuitable001** [unsuitable001/buildozer3#2]
It looks like some of the packages are out of date or has no installation candidate.
See travis CI log - https://travis-ci.org/unsuitable001/buildozer3
Raw Log - https://api.travis-ci.org/v3/job/593916047/log.txt

Now, delete the deprecated installation method of Kivy & replace it with the updated one.

Files need to be changed

`.travis.yml`

Try not to change other files or functionality.
You must pass the CI check.

When opening a PR, please add "Fixes <this_issue_id" at the end of the description.

Happy Coding :smile: :1st_place_medal:

**Comment by georgettica** [comment]
Can I take this issue?

**Comment by unsuitable001** [comment]
Go ahead @georgettica

**Comment by Archeri2000** [comment]
Is @georgettica still working on this issue? If not may I take it?

**Comment by georgettica** [comment]
You may take it.
Sadly I cannot give you any helpful details about this issue.

But good luck!

**Comment by Archeri2000** [comment]
@unsuitable001 From what I can see of the log, it seems that the problem lies with the dockerfile and not with .travis.yml.

I've been playing around with the dockerfile and kivy can be installed fine as long as we add a source to apt, and retrieve a key. This means GPG needs to be installed first, but I can add a command after that to remove gpg so the image takes up less space. However, for open JDK,  Debian 10 (buster) has stopped supporting it. Alternative sources are less official. If you don't mind the use of an alternative source, that is certainly an option. Otherwise, jdk8 is also supported on stretch. Would using a minideb:stretch image be suitable for your needs?

**Comment by unsuitable001** [comment]
yes. you can use stretch @archery2000
